# -*- coding: utf-8 -*-
"""
Created on Mon Oct 15 21:45:05 2018

@author: josephwy
"""
#266 subj areas
#74 common words
subj_areas = ["scidir","agribio","agribiogen","agrocrop","animalandzoo",
              "aquatic","ecovolut","foodsci","forestry","hortic","insect",
              "plant","soilsci","artsandhumanities","artshumangen","history",
              "langandling","mediatechno","biochemgenmolbiol","ageing",
              "biochem","biogen","biophys","biotech","cancres","cellbio",
              "clinicalbio","developbio","endocrinol","genetics","molecbio",
              "molmed","physiology","structbiol","busmanacc","accounting",
              "busintmgmt","busmanaccgen","maninfosys","mantechinnov",
              "marketing","orgbehaviorandhr","stratandstrmngt",
              "tourleishospmngt","chemicaleng","bioengineering","catalysis",
              "chemengin","chemhealthsafe","colloid","filtraseparation",
              "fluflotransferpr","procchemandtech","chemistry","analytchem",
              "chemistrygen","electrochem","inorganicchem","organicchem",
              "physandtheochem","spectroscopy","computerscience","artintell",
              "comptheomat","graphcad","compnet","compscigen","compsciappl",
              "compvis","hardware","humcomp","infosys","signalproc","software",
              "decisionsciences","decscigen","infosysandmngmt",
              "mngmtsciopsres","statprobuncert","design","earth","atmosci",
              "compearthsci","earthscigen","earthsurfproc","econogeo",
              "geochemandpetro","geology","geophysics","geotechengenggeo",
              "oceanography","palaentology","spaceandplanetsci","stratigraphy",
              "economics","econandeconmetr","econgen","finance","energy",
              "energygen","energyeng","fueltech","nucenergyandeng",
              "renewsusenvenrgy","engineering","aerospacesci","autoeng",
              "bioeng","civil","compmech","controlsys","elecandelectroeng",
              "engineergen","industrial","mecheng","mechmat","oceaneng",
              "saferisk","environmental","ecomodelling","ecology",
              "environchem","environeng","environscigen","globandplanchnge",
              "hlthtoximuta","mngmtmonipollaw","natlandcons","pollution",
              "wastemngmtdis","waterscitech","immunolmicrobiol",
              "applmicrobiotech","immunology","immumicrobiogen","microbiology",
              "parasitology","virology","linguistics","materialsscience",
              "biomatreioals","ceramcomp","electronoptic","materialchem",
              "materialscigen","metalandalloy","nanotechno","polymersplastics",
              "surfcoat","mathematics","algebranumtheory","analysis",
              "appliedmaths","computmaths","controlandoptimi","discrmathcombs",
              "geometandtopo","logic","mathphys","mathsgen","modelandsimul",
              "numeranalysis","statsprob","theocompsci","medicinedentistry",
              "anesthpain","cardiol","clinneurol","compalt","critcare",
              "dentist","dermatology","emergencymed","endocrin","forensicmed",
              "gastroenterology","geriatricandgeront","healthinfo",
              "hematology","hepatology","immunallergol","infectious",
              "meddentgen","nephrology","obstetgyn","oncology","ophthalmology",
              "orthoped","otorhino","pathol","perinatol","psychiatry",
              "publichealth","pulmin","radiol","surgery","transplantation",
              "urology","neuroscience","behavneuro","biopsychiatry",
              "cellmolneurosci","cognneuro","developneurosci","endoandautosys",
              "neurology","neuroscigen","sensosys","nursinghealth",
              "emergrescue","mantherapy","midwifery","nursing",
              "nursehealthgen","nutrition","occuptherapy","optometry",
              "phystherapy","podiatry","primcare","radiography","sportssci",
              "pharmatox","drugdiscov","pharmasci","pharamacology","pharmgen",
              "toxicology","philosophy","physics","acoustics",
              "astrandastrophys","optics","conmatphysics","instrumentation",
              "nucandhienerphys","physgen","radiation","statsnonlinphys",
              "surfandinterface","psychology","appliedpsych","clinicpsych",
              "devendedupsych","expandcognpsych","neurosciphypsych",
              "psycholgen","socpsychol","socialsciences","archaeology",
              "develop","education","geoplananddev","health","humfactors",
              "law","libandinfosci","linguandlangu","saferesearch","socscigen",
              "socandpolsci","transportation","sportsrec","vetscimed",
              "vetmed","vetsci",]
 
comm_words = ["about","again","all","almost","also","although","always","am",
              "among","an","and","another","any","are","as","at","be","because"
              ,"been","before","being","between","both","but","by","can",
              "could","did","do","does","done","due","during","each","either",
              "enough","especially","etc","ever","for","found","from","further"
              ,"had","hardly","has","have","having","hence","her","here","him",
              "his","how","however","if","in","into","is","it","its","itself",
              "just","made","mainly","make","might","most","mostly","must",
              "nearly","neither","obtained","of"]
len(subj_areas)